import type { DesignToken } from './validate.js';

const AUTO_GENERATED_HEADER = '// Auto-generated by @adesso-forge/ds-shared — do not edit manually\n';

/**
 * Converts design tokens to SCSS variables.
 *
 * @example
 * toScss([{ name: '--wa-color-brand-500', value: '#0052CC' }])
 * // => '$wa-color-brand-500: #0052CC;'
 */
export function toScss(tokens: DesignToken[]): string {
  const lines = tokens.map((t) => {
    const scssName = t.name.replace(/^--/, '$');
    return `${scssName}: ${t.value};`;
  });

  return AUTO_GENERATED_HEADER + '\n' + lines.join('\n') + '\n';
}

/**
 * Converts design tokens to a TypeScript constants file.
 *
 * @example
 * toTypeScript([{ name: '--wa-color-brand-500', value: '#0052CC' }])
 * // => 'export const waColorBrand500 = "#0052CC" as const;'
 */
export function toTypeScript(tokens: DesignToken[]): string {
  const lines = tokens.map((t) => {
    const tsName = tokenNameToTsConst(t.name);
    return `export const ${tsName} = ${JSON.stringify(t.value)} as const;`;
  });

  return AUTO_GENERATED_HEADER + '\n' + lines.join('\n') + '\n';
}

/**
 * Converts a CSS custom property name to a TypeScript constant name.
 * --wa-color-brand-500 → waColorBrand500
 */
function tokenNameToTsConst(name: string): string {
  return name
    .replace(/^--/, '')
    .replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}
